<?xml version="1.0" encoding="utf-8"?><Database Name="SuperPlus" Class="InventarioBDDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=192.168.1.45\SQLEXPRESS;Initial Catalog=SuperPlus;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SuperPlusConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Areas" Member="Areas">
    <Type Name="Areas">
      <Column Name="IdAreas" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="UNombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Carpeta" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Areas_Articulos" Member="Articulos" ThisKey="IdAreas" OtherKey="IdAreas" Type="Articulos" />
      <Association Name="Areas_SubAreas" Member="SubAreas" ThisKey="IdAreas" OtherKey="IdArea" Type="SubAreas" />
      <Association Name="Areas_Supervision" Member="Supervision" ThisKey="IdAreas" OtherKey="IdAreas" Type="Supervision" />
      <Association Name="Usuarios_Areas" Member="Usuarios" ThisKey="IdUsuario" OtherKey="IdUsuarios" Type="Usuarios" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuarios">
      <Column Name="IdUsuarios" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CURP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ApellidosP" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ApellidosM" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Foto" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FechaDeNacimiento" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdEstado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdMunicipio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdLocalidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RFC" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="NoSS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdPerfil" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="LvlPerfil" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FechaIngreso" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Municipio" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Localidad" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="IdArea" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IdSubArea" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NArea" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="NSArea" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Usuarios_Areas" Member="Areas" ThisKey="IdUsuarios" OtherKey="IdUsuario" Type="Areas" />
    </Type>
  </Table>
  <Table Name="dbo.Articulos" Member="Articulos">
    <Type Name="Articulos">
      <Column Name="IdArticulos" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NombreEmpresa" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdUnidadDeMedida" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IdAreas" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IdMarca" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IdCategorias" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Categoria" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="NombreProveedor" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="PrecioUnitarioPromedio" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="UnidadSAT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClaveSAT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Logo" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Fecha" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaSistema" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Unidad" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Area" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Marca" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdProveedor" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="Articulos_PedidosExternos" Member="PedidosExternos" ThisKey="IdArticulos" OtherKey="IdArticulo" Type="PedidosExternos" />
      <Association Name="Articulos_PedidosInternos" Member="PedidosInternos" ThisKey="IdArticulos" OtherKey="IdArticulo" Type="PedidosInternos" />
      <Association Name="Articulos_TipoDeMovimientos" Member="TipoDeMovimientos" ThisKey="IdArticulos" OtherKey="IdArticulos" Type="TipoDeMovimientos" />
      <Association Name="Areas_Articulos" Member="Areas" ThisKey="IdAreas" OtherKey="IdAreas" Type="Areas" IsForeignKey="true" />
      <Association Name="Categorias_Articulos" Member="Categorias" ThisKey="IdCategorias" OtherKey="IdCategorias" Type="Categorias" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Marca_Articulos" Member="Marca1" ThisKey="IdMarca" OtherKey="IdMarca" Type="Marca" IsForeignKey="true" />
      <Association Name="UnidadDeMedida_Articulos" Member="UnidadDeMedida" ThisKey="IdUnidadDeMedida" OtherKey="IdUnidadDeMedida" Type="UnidadDeMedida" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Categorias" Member="Categorias">
    <Type Name="Categorias">
      <Column Name="IdCategorias" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Categorias_Articulos" Member="Articulos" ThisKey="IdCategorias" OtherKey="IdCategorias" Type="Articulos" />
    </Type>
  </Table>
  <Table Name="dbo.Compra" Member="Compra">
    <Type Name="Compra">
      <Column Name="IdCompra" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MetodoDePago" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClaveProveedor" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NoCompra" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FechaDeIngreso" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ExitenciaInicial" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FechaFinal" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ExitenciaActual" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Coste" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Impuesto" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="IdImpuesto" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IdProveedor" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IdArticulo" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Articulo" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Compra_ExistenciaAlmacenG" Member="ExistenciaAlmacenG" ThisKey="IdCompra" OtherKey="IdCompra" Type="ExistenciaAlmacenG" />
    </Type>
  </Table>
  <Table Name="dbo.Configuracion" Member="Configuracion">
    <Type Name="Configuracion">
      <Column Name="IdConfiguracion" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdPagina" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="RFC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NombreEmpresa" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Vision" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Mision" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Valores" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DireccionHost" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Puerto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Logo" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="LogoTexto" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SesionAbierta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SerCorreo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SerCorreoPort" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SerCorreoUser" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SerCorreoPass" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="DirWeb" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Tipo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Dato2" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Dato3" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Dato4" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Dato1" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Pagina_Configuracion" Member="Pagina" ThisKey="IdPagina" OtherKey="IdPagina" Type="Pagina" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.estados" Member="estados">
    <Type Name="estados">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="clave" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="abrev" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="activo" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="estados_municipios" Member="municipios" ThisKey="id" OtherKey="estado_id" Type="municipios" />
      <Association Name="estados_Proveedores" Member="Proveedores" ThisKey="id" OtherKey="IdEstado" Type="Proveedores" />
    </Type>
  </Table>
  <Table Name="dbo.ExistenciaAlmacenG" Member="ExistenciaAlmacenG">
    <Type Name="ExistenciaAlmacenG">
      <Column Name="IdExistenciaAlmacenG" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdCompra" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NoPedido" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FechaDeIngreso" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ExitenciaInicial" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FechaFinal" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ExitenciaActual" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Coste" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TipoDeOperacion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Compra" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="FechaSistema" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ExistenciaAlmacenG_PedidosInternos" Member="PedidosInternos" ThisKey="IdExistenciaAlmacenG" OtherKey="IdExistenciaAlmacenG" Type="PedidosInternos" />
      <Association Name="Compra_ExistenciaAlmacenG" Member="Compra1" ThisKey="IdCompra" OtherKey="IdCompra" Type="Compra" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Impuesto" Member="Impuesto">
    <Type Name="Impuesto">
      <Column Name="IdImpuesto" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Impuestos" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Porcentaje" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.localidades" Member="localidades">
    <Type Name="localidades">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="municipio_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="clave" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="mapa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ambito" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="latitud" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="longitud" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="lat" Type="System.Decimal" DbType="Decimal(10,7) NOT NULL" CanBeNull="false" />
      <Column Name="lng" Type="System.Decimal" DbType="Decimal(10,7) NOT NULL" CanBeNull="false" />
      <Column Name="altitud" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="carta" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="poblacion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="masculino" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="femenino" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="viviendas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="activo" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="localidades_Proveedores" Member="Proveedores" ThisKey="id" OtherKey="IdLocalidad" Type="Proveedores" />
      <Association Name="localidades_Tienda" Member="Tienda" ThisKey="id" OtherKey="IdLocalidad" Type="Tienda" />
      <Association Name="municipios_localidades" Member="municipios" ThisKey="municipio_id" OtherKey="id" Type="municipios" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Marca" Member="Marca">
    <Type Name="Marca">
      <Column Name="IdMarca" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Marca_Articulos" Member="Articulos" ThisKey="IdMarca" OtherKey="IdMarca" Type="Articulos" />
      <Association Name="Marca_PedidosExternos" Member="PedidosExternos" ThisKey="IdMarca" OtherKey="IdMarca" Type="PedidosExternos" />
      <Association Name="Marca_PedidosInternos" Member="PedidosInternos" ThisKey="IdMarca" OtherKey="IdMarca" Type="PedidosInternos" />
    </Type>
  </Table>
  <Table Name="dbo.municipios" Member="municipios">
    <Type Name="municipios">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="estado_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="clave" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="activo" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="municipios_localidades" Member="localidades" ThisKey="id" OtherKey="municipio_id" Type="localidades" />
      <Association Name="municipios_Proveedores" Member="Proveedores" ThisKey="id" OtherKey="IdMunicipio" Type="Proveedores" />
      <Association Name="municipios_Tienda" Member="Tienda" ThisKey="id" OtherKey="IdMunicipio" Type="Tienda" />
      <Association Name="estados_municipios" Member="estados" ThisKey="estado_id" OtherKey="id" Type="estados" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pagina" Member="Pagina">
    <Type Name="Pagina">
      <Column Name="IdPagina" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Mensaje" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Accion" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Controlador" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Icono" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Pagina_Configuracion" Member="Configuracion" ThisKey="IdPagina" OtherKey="IdPagina" Type="Configuracion" />
      <Association Name="Pagina_PerfilDeUsuario" Member="PerfilDeUsuario" ThisKey="IdPagina" OtherKey="IdPagina" Type="PerfilDeUsuario" />
    </Type>
  </Table>
  <Table Name="dbo.PedidosExternos" Member="PedidosExternos">
    <Type Name="PedidosExternos">
      <Column Name="IdPedidosExternos" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NumeroPedido" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CantidadSolicitada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdUnidadDeMedida" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="UnidadDeMedida" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdMarca" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Marca" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdProveedor" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Proveedor" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="IdArticulo" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Articulo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Articulos_PedidosExternos" Member="Articulos" ThisKey="IdArticulo" OtherKey="IdArticulos" Type="Articulos" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Marca_PedidosExternos" Member="Marca1" ThisKey="IdMarca" OtherKey="IdMarca" Type="Marca" IsForeignKey="true" />
      <Association Name="Proveedores_PedidosExternos" Member="Proveedores" ThisKey="IdProveedor" OtherKey="IdProveedores" Type="Proveedores" IsForeignKey="true" />
      <Association Name="UnidadDeMedida_PedidosExternos" Member="UnidadDeMedida1" ThisKey="IdUnidadDeMedida" OtherKey="IdUnidadDeMedida" Type="UnidadDeMedida" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PedidosInternos" Member="PedidosInternos">
    <Type Name="PedidosInternos">
      <Column Name="IdPedidosInternos" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NumeroPedido" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CantidadSolicitada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadAprobada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="IdUnidadDeMedida" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="UnidadDeMedida" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdMarca" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Marca" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdTienda" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Tienda" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdArticulo" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Articulo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdExistenciaAlmacenG" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Articulos_PedidosInternos" Member="Articulos" ThisKey="IdArticulo" OtherKey="IdArticulos" Type="Articulos" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="ExistenciaAlmacenG_PedidosInternos" Member="ExistenciaAlmacenG" ThisKey="IdExistenciaAlmacenG" OtherKey="IdExistenciaAlmacenG" Type="ExistenciaAlmacenG" IsForeignKey="true" />
      <Association Name="Marca_PedidosInternos" Member="Marca1" ThisKey="IdMarca" OtherKey="IdMarca" Type="Marca" IsForeignKey="true" />
      <Association Name="Tienda_PedidosInternos" Member="Tienda1" ThisKey="IdTienda" OtherKey="IdTienda" Type="Tienda" IsForeignKey="true" />
      <Association Name="UnidadDeMedida_PedidosInternos" Member="UnidadDeMedida1" ThisKey="IdUnidadDeMedida" OtherKey="IdUnidadDeMedida" Type="UnidadDeMedida" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PerfilDeUsuario" Member="PerfilDeUsuario">
    <Type Name="PerfilDeUsuario">
      <Column Name="IdPerfilDeUsuario" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdPagina" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Perfil" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Nivel" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Permisos" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Comentarios" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Pagina_PerfilDeUsuario" Member="Pagina" ThisKey="IdPagina" OtherKey="IdPagina" Type="Pagina" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Proveedores" Member="Proveedores">
    <Type Name="Proveedores">
      <Column Name="IdProveedores" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RazonSocial" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ClaveInterbancaria" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CodigoPostal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdEstado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="IdMunicipio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Municipio" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="IdLocalidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Localidad" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="RFC" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Banco" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NumeroDeCuenta" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="UsoCFDI" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Logo" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Proveedores_PedidosExternos" Member="PedidosExternos" ThisKey="IdProveedores" OtherKey="IdProveedor" Type="PedidosExternos" />
      <Association Name="estados_Proveedores" Member="estados" ThisKey="IdEstado" OtherKey="id" Type="estados" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="localidades_Proveedores" Member="localidades" ThisKey="IdLocalidad" OtherKey="id" Type="localidades" IsForeignKey="true" />
      <Association Name="municipios_Proveedores" Member="municipios" ThisKey="IdMunicipio" OtherKey="id" Type="municipios" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SubAreas" Member="SubAreas">
    <Type Name="SubAreas">
      <Column Name="IdSubAreas" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="NoSubArea" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdArea" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Area" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="UNombre" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="IdEncargado1" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TelefonoE1" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CorreoE1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NEncargado1" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="IdEncargado2" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NEncargado2" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="TelefonoE2" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CorreoE2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdEncargado3" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NEncargado3" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="TelefonoE3" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CorreoE3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Areas_SubAreas" Member="Areas" ThisKey="IdArea" OtherKey="IdAreas" Type="Areas" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Supervision" Member="Supervision">
    <Type Name="Supervision">
      <Column Name="IdSupervision" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TipoSupervicion" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IdAreas" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="nombreUsuario" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Tienda" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Supervision_Supervisor" Member="Supervisor" ThisKey="IdSupervision" OtherKey="IdSupervision" Type="Supervisor" />
      <Association Name="Supervision_Tienda" Member="Tienda1" ThisKey="IdSupervision" OtherKey="IdSupervision" Type="Tienda" />
      <Association Name="Areas_Supervision" Member="Areas" ThisKey="IdAreas" OtherKey="IdAreas" Type="Areas" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Supervisor" Member="Supervisor">
    <Type Name="Supervisor">
      <Column Name="IdSupervisor" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ApellidoP" Type="System.String" DbType="VarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="ApellidoM" Type="System.String" DbType="VarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="IdSupervision" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TipoSupervision" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Supervisor_Tienda" Member="Tienda" ThisKey="IdSupervisor" OtherKey="IdSupervisor" Type="Tienda" />
      <Association Name="Supervision_Supervisor" Member="Supervision" ThisKey="IdSupervision" OtherKey="IdSupervision" Type="Supervision" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Tienda" Member="Tienda">
    <Type Name="Tienda">
      <Column Name="IdTienda" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdSupervisor" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IdSupervision" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="NombreS" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Unombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="LNombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="E1Nombre" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="E2Nombre" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="E3Nombre" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="A1Nombre" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="A2Nombre" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="A3Nombre" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="IdEstado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="IdMunicipio" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Municipio" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="IdLocalidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Localidad" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Calle" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="HApertura" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="HCierre" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Tienda_PedidosInternos" Member="PedidosInternos" ThisKey="IdTienda" OtherKey="IdTienda" Type="PedidosInternos" />
      <Association Name="localidades_Tienda" Member="localidades" ThisKey="IdLocalidad" OtherKey="id" Type="localidades" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="municipios_Tienda" Member="municipios" ThisKey="IdMunicipio" OtherKey="id" Type="municipios" IsForeignKey="true" />
      <Association Name="Supervision_Tienda" Member="Supervision" ThisKey="IdSupervision" OtherKey="IdSupervision" Type="Supervision" IsForeignKey="true" />
      <Association Name="Supervisor_Tienda" Member="Supervisor" ThisKey="IdSupervisor" OtherKey="IdSupervisor" Type="Supervisor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TipoDeMovimientos" Member="TipoDeMovimientos">
    <Type Name="TipoDeMovimientos">
      <Column Name="IdMovimientos" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdArticulos" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="IdUnidadDeMedida" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TipoDeMovimiento" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Articulo" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Unidades" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Articulos_TipoDeMovimientos" Member="Articulos" ThisKey="IdArticulos" OtherKey="IdArticulos" Type="Articulos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UnidadDeMedida" Member="UnidadDeMedida">
    <Type Name="UnidadDeMedida">
      <Column Name="IdUnidadDeMedida" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Unidad" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Estatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdArticulo" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Articulo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="UnidadDeMedida_Articulos" Member="Articulos" ThisKey="IdUnidadDeMedida" OtherKey="IdUnidadDeMedida" Type="Articulos" />
      <Association Name="UnidadDeMedida_PedidosExternos" Member="PedidosExternos" ThisKey="IdUnidadDeMedida" OtherKey="IdUnidadDeMedida" Type="PedidosExternos" />
      <Association Name="UnidadDeMedida_PedidosInternos" Member="PedidosInternos" ThisKey="IdUnidadDeMedida" OtherKey="IdUnidadDeMedida" Type="PedidosInternos" />
    </Type>
  </Table>
</Database>